- README.md
Fix link to English help files to point to the canonical repo rather
than a fork. Also add missing periods to the sentences.
> Fix link to English help files and correct punctuation

- src/help/zaphelp/contents/ui/dialogs/options/dynsslcert.html
Change the key size from 1024 to 2048 to match the one used in the code.
Change done in zaproxy/zaproxy#1690.
> Update Dynamic SSL Certificates page with code change for client certs

- src/help/zaphelp/contents/ui/dialogs/options/view.html
Move the option "Font Size" to be after the output timestamps table,
to have the table immediately after the option "Output Tabs Timestamp
Options".
> Correct table's location in Options Display screen

- src/help/zaphelp/contents/start/concepts/alerts.html
- src/help/zaphelp/contents/ui/tabs/alerts.html
HelpStartConceptsAlerts updated to include mention and link to passive
scanning as a source of alerts, as well as mentioning that scripts can
be a source of alerts.
HelpUiTabsAlerts removed redundant paragraph about alert sources, as
it's already covered in the concepts page. (Also cleaned up line breaks
vs paragraphs.)
Fixes zaproxy/zaproxy#2243
> Core Help - Alerts Topic Updates

- src/help/zaphelp/contents/ui/dialogs/options/database.html
Change "Options Database screen" page to document the option Recovery
Log.
Part of zaproxy/zaproxy#1958 - Allow to disable database (HSQLDB) log
> Document database's option Recovery Log

- src/help/zaphelp/contents/ui/dialogs/options/ascaninput.html
Change "Options Active Scan Input Vectors screen" page to document the
new option All Headers, sub-option of HTTP Headers. Also, replace the
table "Injectable Targets" with entries to make All Headers option a
sub-entry of HTTP Headers.
Part of zaproxy/zaproxy#1959 - Allow to active scan headers of all
requests
> Document active scan's option All Headers

- src/help/zaphelp/contents/ui/dialogs/options/view.html
- src/help/zaphelp/contents/ui/tltoolbar.html
Change "Options Display screen" page to document the option Response
Panel Position and document the options available in the Display option.
(Both the options are based on the documentation from the main tool
bar.)
Change "Top Level Toolbar" page to rename the option Expand Full to Full
Layout.
Part of zaproxy/zaproxy#2374 - Unable to change response tab position
without main tool bar
Part of zaproxy/zaproxy#2361 - Rename tool bar option Expand Full to
Full Layout
> Document some display options

- src/help/zaphelp/contents/ui/dialogs/spider.html
Change "Spider dialog" page to document the option Spider Subtree Only.
Part of zaproxy/zaproxy#2274 - Allow to spider just a site's subtree
> Document spider's option Spider Subtree Only

- src/help/zaphelp/contents/start/concepts/authentication.html
- src/help/zaphelp/contents/start/concepts/concepts.html
- src/help/zaphelp/contents/start/concepts/httpsessions.html
- src/help/zaphelp/contents/start/concepts/sessionManagement.html
- src/help/zaphelp/contents/ui/dialogs/options/httpsessions.html
- src/help/zaphelp/contents/ui/tabs/httpsessions.html
- src/help/zaphelp/contents/ui/tabs/params.html
- src/help/zaphelp/toc.xml
Update help pages and TOC to use HTTP instead of Http.
Related to zaproxy/zaproxy#2467 - Normalise the case of HTTP/S
> Normalise the case of HTTP

- src/help/zaphelp/helpset.hs
- src/help/zaphelp_ar_SA/helpset_ar_SA.hs
- src/help/zaphelp_az_AZ/helpset_az_AZ.hs
- src/help/zaphelp_bs_BA/helpset_bs_BA.hs
- src/help/zaphelp_da_DK/helpset_da_DK.hs
- src/help/zaphelp_de_DE/helpset_de_DE.hs
- src/help/zaphelp_el_GR/helpset_el_GR.hs
- src/help/zaphelp_es_ES/helpset_es_ES.hs
- src/help/zaphelp_fa_IR/helpset_fa_IR.hs
- src/help/zaphelp_fil_PH/helpset_fil_PH.hs
- src/help/zaphelp_fr_FR/helpset_fr_FR.hs
- src/help/zaphelp_hi_IN/helpset_hi_IN.hs
- src/help/zaphelp_hr_HR/helpset_hr_HR.hs
- src/help/zaphelp_hu_HU/helpset_hu_HU.hs
- src/help/zaphelp_id_ID/helpset_id_ID.hs
- src/help/zaphelp_it_IT/helpset_it_IT.hs
- src/help/zaphelp_ja_JP/helpset_ja_JP.hs
- src/help/zaphelp_ko_KR/helpset_ko_KR.hs
- src/help/zaphelp_pl_PL/helpset_pl_PL.hs
- src/help/zaphelp_pt_BR/helpset_pt_BR.hs
- src/help/zaphelp_ro_RO/helpset_ro_RO.hs
- src/help/zaphelp_ru_RU/helpset_ru_RU.hs
- src/help/zaphelp_si_LK/helpset_si_LK.hs
- src/help/zaphelp_sk_SK/helpset_sk_SK.hs
- src/help/zaphelp_sl_SI/helpset_sl_SI.hs
- src/help/zaphelp_sq_AL/helpset_sq_AL.hs
- src/help/zaphelp_sr_CS/helpset_sr_CS.hs
- src/help/zaphelp_sr_SP/helpset_sr_SP.hs
- src/help/zaphelp_ur_PK/helpset_ur_PK.hs
- src/help/zaphelp_zh_CN/helpset_zh_CN.hs
Change helpset files to use as SearchView the class ZapSearchView which
allows to handle search view merge errors more gracefully (i.e. valid
views are still merged and in the end the User Guide shown).
Related to zaproxy/zaproxy#2479 - Show User Guide even if a search view
has errors
> Use custom SearchView for proper error handling

- src/help/zaphelp/contents/ui/dialogs/options/options.html
- src/help/zaphelp/toc.xml
Add the missing entries Extensions, Global Exclude URL, HTTP Sessions
and Language to "Options dialog" page.
Change the options' entry JVM to all upper case in TOC file and correct
the (alphabetic) ordering of the entries Global Exclude URL and HTTP
Sessions.
> Add missing entries to Options dialog page

- src/help/zaphelp/contents/ui/dialogs/options/view.html
Change "Options Display screen" page to document the option Show (local)
CONNECT requests.
Part of zaproxy/zaproxy#2494 - ZAP Proxy is not showing the HTTP CONNECT
Request in history tab
> Document option Show (local) CONNECT requests

- src/help/zaphelp/contents/ui/dialogs/options/ascan.html
Change "Options Active Scan screen" page to correct the meaning of zero
value for the option "Max progress chart in mins", when set to zero the
chart is disabled.
> Correct meaning of chart's option value

- src/help/zaphelp/contents/start/concepts/filters.html
- src/help/zaphelp/contents/ui/dialogs/filter.html
Change "Filters" and "Filter dialog" pages to add a note (based on text
shown in UI) that mentions that the filters have been replaced by
scripts and will be removed in a future version of ZAP.
> Add note about pending removal of Filters

- src/help/zaphelp/contents/start/concepts/authentication.html
- src/help/zaphelp/contents/start/concepts/spider.html
- src/help/zaphelp/contents/ui/tabs/search.html
Change "Authentication", "Search" and "Spider" pages to remove
references to attack menu items that no longer exist (e.g. "Spider
Site"), either by replacing with new menu items or forwarding to
existing dialogues (Active Scan or Spider).
---
Reported in OWASP IRC channel.
> Remove references to menus that no longer exist

- src/help/zaphelp/contents/cmdline.html
Also, just because I wasn't sure where else to write them:
- I wanted to update the [HelpAddonsQuickstartCmdline](https://github.com/zaproxy/zap-core-help/wiki/HelpAddonsQuickstartCmdline) page, but couldn't find the file in the repository...am I missing something?
- Would you consider switching the documentation to Markdown? Seems like it would make the documentation source easier to read, and thus to contribute to.
- Would you consider enabling the Issues on this repository? I've come across some documentation-specific issues/suggestions (i.e. the bullets above), and might be nice to have them co-located here, rather than cluttering the primary repository.
Let me know where I should post these to continue the conversation. Thanks!
> include instructions around where to find the CLI

- src/help/zaphelp/contents/start/concepts/pscan.html
- src/help/zaphelp/contents/ui/dialogs/options/options.html
- src/help/zaphelp/contents/ui/dialogs/options/pscanner.html
- src/help/zaphelp/index.xml
- src/help/zaphelp/map.jhm
- src/help/zaphelp/toc.xml
Document the new passive scanner option that allows to passive scan just
HTTP messages in scope.
Part of zaproxy/zaproxy#3004 - Allow to passive scan just HTTP messages
in scope
> Add help for new passive scanner option

- src/help/zaphelp/contents/ui/dialogs/options/script.html
Change "Options Scripts screen" page to document the character encoding
used to read/write the scripts.
Fix zaproxy/zaproxy#2781 - Document which character encoding is expected
for ZAP scripts
> Document the charset used to read/write scripts

- src/help/zaphelp/contents/start/concepts/pscan.html
- src/help/zaphelp/contents/ui/dialogs/options/pscan.html
Change page "Passive Scan" concept page to explicitly mention that the
passive scanning scans the whole HTTP message, request and response (not
just the latter), merge paragraphs related to automatic functionality
(tagging and raise of alerts) and other minor tweaks.
Change page "Options Passive Scan Tags screen" to fix a typo.
> Tweaks to passive scanner pages

- src/help/zaphelp/contents/ui/tltoolbar.html
Change "Top Level Toolbar" page to correct the name of a option from
"Force User" to "Forced User".
> Correct the name of a main tool bar option

- src/help/zaphelp/contents/ui/dialogs/options/connection.html
Change "Options Connection screen" page to document the option TTL
Successful Queries under the DNS section.
Part of zaproxy/zaproxy#2742 - Allow for override/customization of
Java's "networkaddress.cache.ttl" value
> Document option DNS - TTL Successful Queries

- src/help/zaphelp/contents/start/concepts/scanpolicy.html
Replace the section "Accessed via" with "Configured via" and use the
link that was in the "See also" section for the "Scan Policy Manager"
dialog page (the previous links in "Accessed via" section were removed,
they were linking to other functionality).
> Tweak Scan Policy page

- src/help/zaphelp/contents/ui/tabs/history.html
Change "History tab" page to remove a reference to a context menu item
that no longer exists ("Scan this History").
> Remove menu that no longer exists in History tab

- src/help/zaphelp/contents/credits.html
- src/help/zaphelp/contents/intro.html
- src/help/zaphelp/contents/pentest/pentest.html
- src/help/zaphelp/contents/releases/1_1_0.html
- src/help/zaphelp/contents/releases/2_3_0.html
- src/help/zaphelp/contents/start/concepts/authentication.html
- src/help/zaphelp/contents/start/concepts/sessionManagement.html
- src/help/zaphelp/contents/start/concepts/users.html
- src/help/zaphelp/contents/ui/dialogs/options/jvm.html
- src/help/zaphelp/contents/ui/dialogs/options/view.html
Change HTTP links to HTTPS, when the latter is available.
Fix broken links (page content was no longer the expected).
> Use HTTPS links whenever possible

- src/help/zaphelp/contents/ui/dialogs/options/spider.html
- src/help/zaphelp/contents/ui/dialogs/spider.html
Move the advanced spider option "Maximum children to crawl" to spider
options page. The option will be available in the options panel as well.
Part of zaproxy/zaproxy#3066 - Spidering options in the doc in two place
> Move advanced spider option to options page

- src/help/zaphelp/contents/ui/dialogs/options/localproxy.html
Change "Options Local Proxy screen" page to update the name and
description of the option that (now) removes the unsupported encodings.
Part of zaproxy/zaproxy#2570 - Change proxy option to remove unsupported
encoding
> Update name/description of Local Proxy option

- src/help/zaphelp/contents/ui/dialogs/options/ascan.html
Change "Options Active Scan screen" page to document the option "Inject
plugin ID in header for all active scan requests".
Related to zaproxy/zaproxy#3133 - how disable send X-ZAP-Scan-ID header
> Document option "Inject plugin ID in header"

- src/help/zaphelp/contents/start/concepts/filters.html
- src/help/zaphelp/contents/ui/dialogs/filter.html
Change "Filter dialog" and "Filters" pages to mention that the Replacer
add-on is, along with scripts, the replacement for filters.
> Mention Replacer add-on in Filter notes

- src/help/zaphelp/contents/ui/dialogs/options/localproxy.html
Change "Options Local Proxy screen" page to document the option "Behind
NAT".
Related to:
- zaproxy/zaproxy#3329 - Allow to set the Local Proxy behind NAT
- zaproxy/zaproxy#2318 - ZAP Error [java.net.SocketTimeoutException]:
Read timed out when running on AWS EC2 instance
> Document Behind NAT Local Proxy option

- src/help/zaphelp/contents/ui/tabs/params.html
Update params tab content to include details about response headers
which are now included as part of
https://github.com/zaproxy/zaproxy/pull/3317.
Related to zaproxy/zaproxy#1644
> Update Params Tab Info

- src/help/zaphelp/contents/ui/dialogs/options/localproxy.html
Change "Options Local Proxy screen" page to mention from where the
public IP address, of the AWS EC2 instance, is obtained.
> Tweak Behind NAT Local Proxy option

- README.md
Remove markdown formatting and text from a link that no longer exists.
> Tweak README's first phrase

- src/help/zaphelp/contents/cmdline.html
Change "Command Line" page to mention that the -config options are
applied in the order they are specified.
Related to zaproxy/zaproxy#3330 - Apply config arguments in the order
specified
> Document change in behaviour of -config option

- src/help/zaphelp/contents/ui/dialogs/options/connection.html
Change "Options Connection screen" page to document the option Default
User Agent.
Related to zaproxy/zaproxy#1768 - Update to use a more recent user-agent
> Document Default User Agent connection option

- src/help/zaphelp/contents/ui/dialogs/options/connection.html
- src/help/zaphelp/contents/ui/dialogs/options/localproxy.html
Change pages "Options Local Proxy screen" and "Options Connection
screen" to document the options Security Protocols.
Part of zaproxy/zaproxy#3359 - Missing Help details Options Connection
screen
Related to zaproxy/zaproxy#968 - Allow to choose the enabled SSL/TLS
protocols
> Document Security Protocols options

- src/help/zaphelp/contents/ui/tabs/ascan.html
- src/help/zaphelp/toc.xml
Fix broken link in Active Scan tab page.
Add the Callback Address option panel to the TOC.
> Fix broken link and add an option panel to TOC

- src/help/zaphelp/contents/releases/2_7_0.html
Add an entry to the release notes about API breaking changes and
document the change of view context/contextList.
Part of zaproxy/zaproxy#3353 - ZAP API View:contextList method returns a
string instead of JSON list
> Document contextList API breaking change

- src/help/zaphelp/contents/ui/dialogs/options/connection.html
- src/help/zaphelp/contents/ui/dialogs/options/localproxy.html
Change pages "Options Local Proxy screen" and "Options Connection
screen" to mention that SSLv2Hello must be selected with other SSL/TLS
versions.
Part of zaproxy/zaproxy#3410 - Do not allow to choose just SSLv2Hello
> Update docs to mention SSLv2Hello restrictions

- src/help/zaphelp/contents/ui/dialogs/options/spider.html
Change Options Spider screen page to document the spider option Maximum
parse size.
Part of zaproxy/zaproxy#1313 - Spider - Allow to configure the size
limit of parseable responses
> Document Maximum parse size spider option

- src/help/zaphelp/contents/ui/dialogs/options/spider.html
Change Options Spider screen page to update the name of the option that
allows to manage the domains that are in spider's scope, also, mention
that it supports string literals and regular expressions.
> Tweak spider option Domains Always in Scope

- src/help/zaphelp/contents/start/concepts/alerts.html
Change Alerts concept page to mention that the alert overrides file can
also be set through the API.
Part of zaproxy/zaproxy#3443 - Expose Alerts options through the ZAP API
> Update Alerts concept page

- src/help/zaphelp/contents/start/concepts/api.html
Change API concept page to mention that the API is only accessible, by
default, to the local machine, not all machines that can proxy through
ZAP.
> Update API concepts page

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to add the new API endpoints that allow to
set/get the Alerts options.
Part of zaproxy/zaproxy#3443 - Expose Alerts options through the ZAP API
> Add new API endpoints to release notes

- src/help/zaphelp/contents/ui/tlmenu/tools.html
Change The Tools menu page to document the Browse API menu item.
Related to zaproxy/zaproxy#3467 - Use local proxy address for Browse API
menu
> Document Browse API menu item

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to add the changed API endpoint core view
"urls", now allows to filter by base URL.
Part of zaproxy/zaproxy#3457 - Allow to filter core view "urls" by base
URL
> Add changed API endpoint to release notes

- src/help/zaphelp/contents/cmdline.html
- src/help/zaphelp/contents/ui/tlmenu/help.html
Updated /ui/tlmenu/help.html to include information about the recently added "Support Info..." help menuitem.
Updated /zaphelp/contents/cmdline.html to include information about the recently added "-suppinfo" CLI switch.
Fixes zaproxy/zaproxy#3460
> Add info related to new Help Support Info menuitem

- src/help/zaphelp/contents/ui/tabs/spider.html
Change Spider tab to mention what is shown under the Messages tab and
explain the meaning of the column Processed.
Part of zaproxy/zaproxy#3392 - Show all messages sent by the Spider
> Update Spider tab page

- src/help/zaphelp/contents/ui/tlmenu/analysis.html
- src/help/zaphelp/contents/ui/tlmenu/edit.html
- src/help/zaphelp/contents/ui/tlmenu/file.html
- src/help/zaphelp/contents/ui/tlmenu/help.html
- src/help/zaphelp/contents/ui/tlmenu/report.html
- src/help/zaphelp/contents/ui/tlmenu/tlmenu.html
- src/help/zaphelp/contents/ui/tlmenu/view.html
Correct the labels of top level menus and menu items (e.f. different
case, missing or different words).
Document some missing menu items, reorder and remove one that was no
longer in the menu.
> Correct labels of top level menus

- src/help/zaphelp/contents/start/concepts/addons.html
- src/help/zaphelp/contents/ui/dialogs/options/checkforupdates.html
- src/help/zaphelp/contents/ui/dialogs/options/ext.html
Change Options Extensions screen page to remove outdated information
(the packaged extensions are no longer loaded by ZAP, superseded by
add-ons) and mention that the add-ons can provide extensions.
Update Add-ons concepts page with the directories used to load the
add-ons (moved and adapted from Options Extensions screen page).
Update Options Check for Updates screen page to point to the concepts
page when referring to the default directories.
> Update Extension/Add-on pages

- src/help/zaphelp/contents/start/proxies.html
Change Configuring Proxies page to include the steps on how to configure
Firefox's outgoing proxy on Linux (different menu and menu item than
Windows).
> Update Configuring Proxies for Firefox on Linux

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to add the new API endpoint that allows to
import a scan policy.
Part of zaproxy/zaproxy#1604 - Import policy file via API
> Add new API endpoint to release notes

- src/help/zaphelp/contents/ui/dialogs/options/dynsslcert.html
Change Dynamic SSL Certificates options page to correct the name of the
tab when importing ZAP's Root CA cert into Firefox ("Authorities tab"
instead of "Trusted root certificates tab"), also, correct case of
button label.
Related to zaproxy/zaproxy#3724 - Wrong step in Getting Started Guide
> Correct tab name when importing root CA cert

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to add the new API endpoint that allows to
get the home directory currently used by ZAP.
Part of zaproxy/zaproxy#3367 - Expose ZAP's home dir path through the
ZAP API
> Add API endpoint zapHomePath to release notes

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to add the changed API endpoint ascan view
scans, now returns the total number of alerts raised and messages sent
during each scan.
Part of zaproxy/zaproxy#3782 - Add msg and alert count to active scans
API view
> Add changed API view ascan/scans to release notes

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to add the new API core action deleteAlert.
Part of zaproxy/zaproxy#3676 - Delete single Alert using the api
> Add API action deleteAlert to release notes

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to add the new API core views messagesById and
messagesHarById.
Part of zaproxy/zaproxy#3514 - Allow to obtain multiple messages by ID
> Add API views messages[Har]ById to release notes

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to mention the (potential) breaking change
done to API core view setOptionUseProxyChain.
Part of zaproxy/zaproxy#3696 - Correct API response for outgoing proxy
changes
> Add API breaking change to release notes

- src/help/zaphelp/contents/ui/dialogs/options/jvm.html
- src/help/zaphelp/contents/ui/dialogs/options/view.html
Change Options Display screen page to use Java 8 JavaDocs (and make it a
link).
Change Options JVM screen page to refer just to Java 8 docs (Java 7 no
longer works).
Part of zaproxy/zaproxy#3470 - Move to using Java 8
> Update doc links to refer to Java 8

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to add the new API ascan action skipScanner.
Part of zaproxy/zaproxy#3910 - Allow to skip scanners through the API
> Add API action skipScanner to release notes

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to mention the normalisation of form-based
login URL validation/usage.
Part of zaproxy/zaproxy#3907 - Normalise form-based login URL
validation/usage
> Add form-based URL usage change to release notes

- src/help/zaphelp/contents/releases/2_7_0.html
Change Release 2.7.0 page to add the new API spider view and action for
the option accepts cookies.
Related to zaproxy/zaproxy#3395 - Add option to spider anonymously with
a session
> Add new API spider action/view to release notes

- src/help/zaphelp/contents/ui/dialogs/options/language.html
Change Options language screen page to document the option Use system's
locale for formatting.
Part of zaproxy/zaproxy#3587 - Allow to use system's locale for
formatting
> Document the formatting locale option

- src/help/zaphelp/contents/ui/dialogs/session/sessprop.html
Change Session Properties dialogue page to mention that the Exclude from
Proxy option now applies to the local proxies (not just main local
proxy).
Part of zaproxy/zaproxy#4062 - Honour proxy exclusions in additional
proxies
> Mention local proxies in Exclude from Proxy

- src/help/zaphelp/contents/releases/2_8_0.html
Add an entry to the release notes about API breaking changes and
document the change of the data returned by the authentication view.
Part of zaproxy/zaproxy#4097 - python api returns the wrong content for
authentication.get_authentication_method()
> Document authentication API breaking change

- src/help/zaphelp/contents/releases/2_8_0.html
Document the change of the structure returned by the "alertsSummary"
core view.
Part of zaproxy/zaproxy#4111 - ZAP Python API:
zap.context.alerts_summary() returns 0
> Document alerts summary API breaking change

- src/help/zaphelp/contents/ui/dialogs/options/jvm.html
Change Options JVM screen page to mention the environment variable used
when reading the file .ZAP_JVM.properties.
Part of zaproxy/zaproxy#4004 - zap.bat should use %USERPROFILE% instead
of %HOMEDRIVE%%HOMEPATH%
> Mention env var used in Windows for JVM options

- src/help/zaphelp/contents/ui/dialogs/addalert.html
- src/help/zaphelp/contents/ui/dialogs/options/ascaninput.html
Update pages Add Alert dialog and Active Scan Input Vectors to document
how the array parameters are identified.
Part of zaproxy/zaproxy#2496 - ZAP only report the first alert in array
> Document how array parameters are identified

- src/help/zaphelp/contents/ui/dialogs/options/localproxy.html
Change Options Local Proxies screen page to correct the mention to the
screen itself (was using the name of other screen).
> Fix typo in Local Proxies page

- src/help/zaphelp/contents/ui/dialogs/options/localproxy.html
Change Options Local Proxies screen page to document that the local
proxies can be used as intercepting proxies, for HTTPS using SNI.
Part of zaproxy/zaproxy#1015 - Support Server Name Indication
---
Based on https://github.com/zaproxy/zap-extensions/wiki/HelpAddonsSniTerminatorSniTerminator
> Document SNI capability in Local Proxies

- src/help/zaphelp/contents/releases/2_8_0.html
Change Release 2.8.0 page to mention that the API core views alerts and
numberOfAlerts will now require a valid risk ID.
Part of zaproxy/zaproxy#4113 - Validate risk ID in core API views
> Document potential breaking change in API views

- src/help/zaphelp/contents/ui/dialogs/options/spider.html
Change Options Spider screen page to use current functionality as
examples when describing the crawl depth calculation, the menus Spider
URL and Spider site are no longer enabled/available.
> Tweak Spider options page

- src/help/zaphelp/contents/cmdline.html
- src/help/zaphelp/contents/releases/2_8_0.html
Change pages Command Line and Release 2.8.0 to document the change to
-dir command line argument.
Part of zaproxy/zaproxy#4226 - Prevent use of install dir as home dir
> Document change to -dir command line argument

- src/help/zaphelp/contents/ui/dialogs/options/spider.html
Change Options Spider screen page to mention the meaning of zero value
for maximum depth to crawl.
Part of zaproxy/zaproxy#4265 - Unable to spider with unlimited depth
> Update description of spider option max depth

- src/help/zaphelp/contents/ui/dialogs/enc_dec.html
- src/help/zaphelp/contents/ui/dialogs/options/dynsslcert.html
Fix typos in the pages "Dynamic SSL Certificates" and "Encode / Decode /
Hash dialog".
Reported by: https://crowdin.com/profile/andresitorresm
> Fix typos reported in Crowdin

- src/help/zaphelp/contents/ui/dialogs/options/api.html
Change Options API screen page to use the new label of the option that
enables the Web UI.
Part of zaproxy/zaproxy#4313 - Tweak label of API option
> Update label of API option

- src/help/zaphelp/contents/ui/dialogs/enc_dec.html
Mention the new fields/functionality, in Encode/Decode sections add a
mention to fields of HTML/JavaScript and add sections for Illegal UTF-8
and Unicode.
Part of zaproxy/zaproxy#1012 and zaproxy/zaproxy#4122.
> Update Encode / Decode / Hash dialog help page

- src/help/zaphelp/contents/ui/dialogs/man_req.html
- src/help/zaphelp/contents/ui/dialogs/options/connection.html
- src/help/zaphelp/contents/ui/dialogs/options/spider.html
- src/help/zaphelp/contents/ui/dialogs/resend.html
- src/help/zaphelp/contents/ui/tlmenu/edit.html
- src/help/zaphelp/contents/ui/tlmenu/tlmenu.html
Per zaproxy/zaproxy#1161 (comment)
- Updated Edit and Top Level menu help content so that it covers the current menu items
- Updated Options Connection screen, manual request, resend, and spider help content so that it covers "Enable (Global) HTTP State"
Fixes zaproxy/zaproxy#4280
> Update Edit Menu & Options Connection Screen Entries

- src/help/zaphelp/contents/releases/2_8_0.html
Change Release 2.8.0 page to add the API core action "snapshotSession",
now allows to specify a name and overwrite files.
Part of zaproxy/zaproxy#4365 - Allow to specify a name for session
snapshot through the API
> Add snapshotSession API action to release notes

- src/help/zaphelp/contents/releases/2_8_0.html
Change Release 2.8.0 page to add the new context API view that allows to
obtain the URLs of a context.
Part of zaproxy/zaproxy#4364 - Allow to obtain context's URLs through
the API
> Add urls context API view to release notes

- src/help/zaphelp/contents/ui/tabs/sites.html
Change Sites tab to mention the Contexts tree.
Tweak existing headers to be under the Sites tree entry.
> Mention Contexts tree in Sites tab page

- src/help/zaphelp/contents/start/concepts/contexts.html
- src/help/zaphelp/contents/ui/dialogs/session/contexts.html
Update pages Contexts and Session Context screens to specify how the
regular expression is checked against the URL (must match). Also,
capitalise the names of the panels in the Session Context screens.
---
Pointed out in the IRC channel some time ago.
> Mention how regexes are checked for contexts

- src/help/zaphelp/contents/ui/dialogs/addbreak.html
Change Add/Edit Break Point dialog page to mention the validation done
when the break point contains a fragment identifier.
Part of zaproxy/zaproxy#4277 - Warn if a # is specified in a break point
URL
> Mention fragment validation in break points

- src/help/zaphelp/contents/ui/tabs/httpsessions.html
Change HTTP Sessions tab page to document the pop up menu item that
allows to copy the value of the session to the clipboard.
Part of zaproxy/zaproxy#1655 - Copy Session Token from Http Sessions tab
to clipboard
> Add copy session context menu to HTTP Sessions tab

- src/help/zaphelp/contents/start/concepts/authentication.html
- src/help/zaphelp/contents/ui/dialogs/session/context-auth.html
- src/help/zaphelp/contents/ui/tabs/history.html
- src/help/zaphelp/contents/ui/tabs/search.html
- src/help/zaphelp/contents/ui/tabs/sites.html
Change help pages Authentication and Session Context Authentication to
mention the JSON-based authentication method.
Mention the "flag" pop up menu item in tabs History, Search, and Sites.
Part of zaproxy/zaproxy#2439 - Configure Authentication with Json object
> Update help for JSON-based authentication

- src/help/zaphelp/contents/ui/dialogs/advascan.html
- src/help/zaphelp/contents/ui/dialogs/spider.html
Tweak the labels per changes in core, to follow title capitalisation.
Related to zaproxy/zaproxy#4648.
> Tweak Spider/Active Scan dialogues' labels

- src/help/zaphelp/contents/releases/2_8_0.html
Change Release 2.8.0 page to add the new script API view that allows to
list the script types available.
Part of zaproxy/zaproxy#4688 - Allow to view script types through the
API
> Add listTypes script API view to release notes

- src/help/zaphelp/contents/ui/dialogs/options/pscan.html
Change Options Passive Scan Tags screen to stop using configuration when
referring to tags.
Part of zaproxy/zaproxy#4668 - Make Passive Scan Tags management cleaner
> Remove configuration usage in passive scan tags

- src/help/zaphelp/contents/releases/2_8_0.html
Change Release 2.8.0 page to mention that context API actions
includeContextTechnologies and excludeContextTechnologies will now
accept a string with spaces between the names and commas.
Part of zaproxy/zaproxy#4767 - Be more lenient when parsing techs
through the API
> Add context API changes to release notes

- src/help/zaphelp/contents/ui/tabs/spider.html
Remove button that no longer exists in the latest versions (>=2.7.0),
the Messages tab is now always visible.
> Remove button from Spider tab help page

- src/help/zaphelp/contents/credits.html
Fix links leading to 404 or redirections:
- Update guttula's twitter account.
- Remove extra `/` in JBroFuzz link.
- Remove link to SwingX home, no longer exists.
- Correct link to Crawljax home (not using HTTPS nor www subdomain).
> Fix broken links and address redirections

- src/help/zaphelp/contents/credits.html
- src/help/zaphelp/contents/intro.html
- src/help/zaphelp/contents/paros.html
Remove links to parosproxy.org, the site is no longer about Paros proxy.
For the Paros Proxy help page link to the project under Source Forge
(which at some point the site was redirecting to).
> Remove links to parosproxy.org

- src/help/zaphelp/contents/releases/2_8_0.html
Change Release 2.8.0 page to add the new API httpSessions view/actions
that allow to manage the default session tokens.
Part of zaproxy/zaproxy#4997 - Allow to manage default session tokens
> Add new httpSessions endpoints to release notes

- src/help/zaphelp/contents/ui/dialogs/options/ruleconfig.html
Add rules `rules.csrf.ignore.attname`, `rules.csrf.ignore.attvalue`,
and `rules.domains.trusted`.
Part of zaproxy/zaproxy#3115 and zaproxy/zaproxy#5041.
> Update Rule Configuration options page

- src/help/zaphelp/contents/releases/2_8_0.html
- src/help/zaphelp/contents/ui/dialogs/session/context-auth.html
Update release notes (for API endpoint) and the Session Context
Authentication screen to mention that the users are no longer deleted
when the authentication method is changed.
Part of zaproxy/zaproxy#1067 - User conversion between changes of
AuthenticationMethods
> Update authentication method behaviour on change

- src/help/zaphelp/contents/releases/2_8_0.html
Update release notes to mention the change in the JSON report, the
`site` property will always by an array.
Part of zaproxy/zaproxy#5162 - Inconsistent JSON report format
> Mention breaking change in JSON report

- src/help/zaphelp/map.jhm
- src/help/zaphelp/toc.xml
Remove mappings that point to inexistent files.
Remove commented TOC entry that was using one of the removed mappings.
> Remove invalid mappings

- src/help/zaphelp/contents/releases/2_8_0.html
Change Release 2.8.0 page to add the new API pscan view/action that
allows to get/set the max alerts per rule.
Part of zaproxy/zaproxy#5181 - Add max alerts per rule option to the API
> Add new pscan endpoints to release notes

- src/help/zaphelp/contents/releases/2_8_0.html
Follow-up to:
https://github.com/zaproxy/zap-core-help/pull/215
https://github.com/zaproxy/zaproxy/pull/5166
In the API section I also removed two spurious spaces on the setOptionAddQueryParam section.
> Add Client Cert CLI and API details to release notes

- src/help/zaphelp/contents/releases/2_8_0.html
Update release notes to mention that the core alert API endpoints were
deprecated.
Done in zaproxy/zaproxy#4833 - Added alert api endpoints
> Mention deprecation of core alert API endpoints

- src/help/zaphelp/contents/releases/2_8_0.html
Change Release 2.8.0 page to add the new autoupdate view that allows to
get a list with the local add-ons.
Part of zaproxy/zaproxy#5236 - Expose the local add-ons through the ZAP
API
> Add new autoupdate endpoint to release notes

- addOns/addOns.gradle.kts
The generation of the ZapVersions.xml data will be done in the zap-admin
repository when needed.
> Remove ZapVersions configuration

- addOns/help/src/main/javahelp/contents/cmdline.html
And the -nostdout option which was also missing :)
> Updated help for cert cmdline options

- addOns/help/src/main/javahelp/contents/releases/2_8_0.html
> Added Source Code Restructuring and Headless Browser sections

- addOns/help/src/main/javahelp/contents/releases/2_8_0.html
I put the headless browser support right in the middle of the cmd line changes - my bad :(
Will rerelease this once its merged.
Also move the filter removal section lower as I think its less important.
> Corrected release notes

- addOns/help/src/main/javahelp/contents/start/proxies.html
Mention the requirements to proxy localhost with the newer versions of
Chrome and Firefox.
Use new panel/section names for Firefox steps and mention that SSL Proxy
should be configured as well.
> Update proxy config steps

- addOns/help/src/main/javahelp/contents/ui/dialogs/options/certificate.html
- addOns/help/src/main/javahelp/contents/ui/dialogs/options/options.html
The Certificate panel is now uses the full name "Client Certificate"
> "Client Certificate" updates

- addOns/help/src/main/javahelp/contents/credits.html
Per: https://github.com/zaproxy/zap-extensions/pull/2108
> Add ouaibe to credits

- addOns/help/src/main/javahelp/contents/cmdline.html
Indicate that it's used the ID of the add-on in `-addoninstall`
and `-addonuninstall`.
Part of zaproxy/zaproxy#5655.
> Tweak description of add-on command line args

- addOns/help/src/main/javahelp/contents/ui/dialogs/session/context-auth.html
Mention the new field added to form/JSON auth methods which allows to
specify the login page, used to obtain a new session and regenerate
anti-csrf tokens.
Part of zaproxy/zaproxy#4963 - Allow to specify the URI of the login
page
> Mention login page in form/JSON auth methods

- addOns/help/src/main/javahelp/contents/releases/2_9_0.html
Update 2.9.0 release notes to mention the custom script variables and
related API endpoints.
> Mention custom script variables in release notes

- addOns/help/src/main/javahelp/contents/releases/2_9_0.html
In follow-up to https://github.com/zaproxy/zap-extensions/pull/2240
> Add pscan rule promotions to 2.9 release notes

- addOns/help/src/main/javahelp/contents/addons/introduction.html
- addOns/help/src/main/javahelp/contents/start/concepts/addons.html
- addOns/help/src/main/javahelp/index.xml
- addOns/help/src/main/javahelp/toc.xml
- commonFiles/src/main/resources/map.jhm
Rename its directory to be plural (`addons`), tweak the title/heading,
and set the TOC icon to the one used for the Manage Add-ons dialogue.
> Tweak main add-ons page

- README.md
- addOns/addOns.gradle.kts
- addOns/help/help.gradle.kts
Update add-on plugin to 0.3.0:
- Specify the repo URL in the add-on manifest.
- Change info URL to point to the help page.
- Remove wiki gen configurations, no longer needed.
Set minimum ZAP version to 2.9.0.
Update online help link in the README to the new location.
> Update add-on plugin, help links, and ZAP version

- addOns/help/src/main/javahelp/contents/ui/dialogs/options/pscanner.html
- addOns/help/src/main/javahelp/contents/ui/dialogs/scanpolicy.html
Move table header in passive scanner options to the previous heading,
tables with multiple headers are not properly rendered when converted
to Markdown.
Remove misplaced colon and add a paragraph to the scan policy dialogue
note.
> Tweak table and note

- addOns/help/src/main/javahelp/contents/credits.html
Per: https://github.com/zaproxy/zaproxy/pull/5814#issuecomment-580788705
> Add Akshath Kothari to credits

- addOns/help/src/main/javahelp/contents/credits.html
Per https://github.com/zaproxy/zaproxy/pull/5930#issuecomment-611267098
> Add Karl Dalley to Credits

- addOns/help/src/main/javahelp/contents/cmdline.html
Be explicit that the executable will not use the command line arguments.
---
From OWASP ZAP User Group: https://groups.google.com/d/topic/zaproxy-users/ps1Esc6YX2o/discussion
> Add note about exe and command line args

- addOns/help/src/main/javahelp/contents/credits.html
Per: https://github.com/zaproxy/zaproxy/pull/6065#issuecomment-655563555
> Add Jannik Hollenbach

- addOns/help/src/main/javahelp/contents/credits.html
- addOns/help/src/main/javahelp/contents/intro.html
Updated core team.
Added note about automation and links to the main website.
Will fix https://github.com/zaproxy/zaproxy-website/issues/138 when
deployed.
> Credit and website link tweaks

- addOns/help/src/main/javahelp/contents/credits.html
Per: https://github.com/zaproxy/zaproxy/pull/5901#issuecomment-711431629
> Add Mahmoud Khalil to credits

- addOns/help/src/main/javahelp/contents/credits.html
As it no longer exists - change suggested by Dave Wichers.
> Remove Aspect Security

- addOns/help/src/main/javahelp/contents/addons/introduction.html
- addOns/help/src/main/javahelp/contents/intro.html
- addOns/help/src/main/javahelp/contents/start/features/ascan.html
- addOns/help/src/main/javahelp/contents/start/features/authentication.html
- addOns/help/src/main/javahelp/contents/start/features/features.html
- addOns/help/src/main/javahelp/contents/start/features/marketplace.html
- addOns/help/src/main/javahelp/contents/start/features/pscan.html
- addOns/help/src/main/javahelp/contents/start/features/scripts.html
- addOns/help/src/main/javahelp/contents/start/features/spider.html
- addOns/help/src/main/javahelp/contents/ui/overview.html
- addOns/help/src/main/javahelp/index.xml
- addOns/help/src/main/javahelp/toc.xml
- commonFiles/src/main/resources/map.jhm
Example screenshot:
Tried adding a video icon but it didnt look quite right, so dropped it.
Was also thinking of adding a link off the first page to https://www.zaproxy.org/videos/
Any feedback?
> Add video links

- addOns/help/src/main/javahelp/contents/releases/2.10.0.html
Update versions for:
- Bouncy Castle;
- JFreeChart.
Remove Commons Validator and Nashorn Sandbox, not part of the public API
(the latter is also no longer bundled).
Mention major update of Log4j library.
> Update libs in 2.10 rel notes

- addOns/help/src/main/javahelp/contents/credits.html
Per: https://github.com/zaproxy/zap-extensions/pull/2666#issuecomment-823285104
Also fixed a previously introduced typo (`herf` &gt; `href`).
> Add theamanrawat

- .github/workflows/crowdin-upload-files.yml
- .gitignore
- RELEASING.md
- addOns/addOns.gradle.kts
- gradle/crowdin.yml
Change release process to upload the files to Crowdin as part of the
(main) add-on release.
Add workflow to trigger the upload of the files, to allow to start to
translate the files before the actual release.
> Upload files to Crowdin on release and manually

- addOns/addOns.gradle.kts
- addOns/help/CHANGELOG.md
- addOns/help/gradle.properties
Keep a reference to the project's add-on extension to reference in the
release task.
Reset the release state of the help add-on, to trigger later.
Update the changelog to mention the update for 2.11.
> Fix release of add-ons and other tweaks

- addOns/addOns.gradle.kts
- addOns/help/gradle.properties
- build.gradle.kts
Set the add-ons to use 2.11 (SNAPSHOT).
Change release state to trigger the release of help add-on.
> Update add-ons to ZAP 2.11 and release main

- addOns/addOns.gradle.kts
- build.gradle.kts
Use main release, already available.
> Stop using ZAP snapshot

- addOns/help/CHANGELOG.md
- addOns/help/gradle.properties
- addOns/help/src/main/javahelp/contents/releases/2.11.1.html
- addOns/help/src/main/javahelp/contents/releases/releases.html
- addOns/help/src/main/javahelp/index.xml
- addOns/help/src/main/javahelp/toc.xml
Add the releases notes for the new ZAP version.
Update changelog and version for release.
> Add release notes for 2.11.1 and prepare release

- addOns/help/CHANGELOG.md
- addOns/help/gradle.properties
- addOns/help/src/main/javahelp/contents/releases/2.11.1.html
- commonFiles/src/main/resources/map.jhm
Mention that the add-ons are also updated.
Add missing map entry for the 2.11.1 release page.
Update changelog and version for release.
> Update 2.11.1 release notes and prepare release

- addOns/help/src/main/javahelp/contents/releases/2.12.0.html
Changes for https://github.com/zaproxy/zaproxy/pull/7068
I also changed to use # in the help to match the Gradle file.
> Updated help with 2.4.x deprecations

- addOns/help/src/main/javahelp/contents/credits.html
Adding name for contribution regarding PR https://github.com/zaproxy/zap-extensions/pull/3619
Signed-off-by: LakiG <garg.lakshya@gmail.com>
> Add credit for LakiG

- addOns/help/src/main/javahelp/contents/releases/2.12.0.html
Add `proxy.pac` to the list of deprecated core endpoints.
Part of zaproxy/zaproxy#7240.
> Update release notes with deprecated API endpoint

- addOns/help/src/main/javahelp/contents/releases/2.12.0.html
Update with:
- More add-ons added for the first time (remove Network, already included in the previous release, even if didn't do much);
- Add-ons removed;
- Versions of libraries updated;
- Library removed;
Mention the Import/Export and Requester add-ons.
Remove the versions of moved libraries (they are using newer versions).
> Update 2.12 release notes

- addOns/addOns.gradle.kts
- build.gradle.kts
Use main release which is already available.
> Remove usage of ZAP snapshot

- addOns/help/CHANGELOG.md
- addOns/help/src/main/javahelp/contents/ui/dialogs/session/contexts.html
- CHANGELOG > Added note.
- contexts.html > Added warning note.
Part of zaproxy/zaproxy#7649, also see zaproxy/zap-extensions#4323
> Add help warning about inclusion of default ports

- addOns/help/src/main/javahelp/contents/start/proxies.html
Add missing quote to close the label and correct the case to match exactly what's shown in the UI.
Reported in Crowdin:
https://crowdin.com/translate/owasp-zap-help/34257/engb-es?filter=basic&value=0#q=2492728
> Add missing quote and correct case in UI label

- addOns/help/src/main/javahelp/contents/cmdline.html
Remove the entries that allow to configure the main local proxy and link to Network help page instead, to avoid duplicating and to keep them up-to-date along with the code.
> Link to Network Command Line help page

- addOns/help/src/main/javahelp/contents/cmdline.html
- addOns/help/src/main/javahelp/contents/start/features/addons.html
- addOns/help/src/main/javahelp/contents/start/features/api.html
- addOns/help/src/main/javahelp/contents/start/features/ascan.html
- addOns/help/src/main/javahelp/contents/start/features/pscan.html
- addOns/help/src/main/javahelp/contents/start/pentest.html
- addOns/help/src/main/javahelp/contents/start/start.html
Official video links are added to html files for additional references and ease of navigation. These video links are gathered from https://www.zaproxy.org/videos-list/ containing the same html format of other videos from other documentation found on www.zaproxy.org.
The only document that did not contain a video link was /addOns/help/src/main/javahelp/contents/start/features/api.html, which contains an additional link under the section 'See also' that provides a reference to the official ZAP API documentation located at https://www.zaproxy.org/docs/api/#introduction.
> Add video links to contents

- addOns/help/CHANGELOG.md
- addOns/help/src/main/javahelp/contents/releases/1.1.0.html
Link to the wiki which still has the homepage (latest site gives 404).
> Update OWASP ZAP homepage link

- addOns/help/CHANGELOG.md
- addOns/help/src/main/javahelp/contents/start/proxies.html
This PR add a section in the user guide on how to configure proxy using Gnome Settings GUI.
> Docs: Add Gnome proxy settings user guide

- addOns/help/CHANGELOG.md
- addOns/help/src/main/javahelp/contents/start/features/tags.html
Help for https://github.com/zaproxy/zaproxy/pull/8673
> Added History -> Alert tag details

- addOns/help/src/main/javahelp/contents/releases/2.16.0.html
I think the unpublished URLs are right, but some of them might need tweaking
> Add 2.16 headline summaries

- addOns/help/src/main/javahelp/contents/ui/dialogs/options/ascan.html
Enclosed the paragraph following each `<H3>` tag in the `ui/dialogs/options/ascan.html` file with `<p>` tags, such as [`paros.html`](https://github.com/zaproxy/zap-core-help/blob/cab5bda4571eb230988c4416ffe1c9aea99cd219/addOns/help/src/main/javahelp/contents/paros.html).
This change fixes an issue where translation units were split mid-sentence, which caused problems for languages with different grammar from English, such as Japanese. Now translators can work with complete sentences for better accuracy.
> ascan.html: Add `p` tags to each appropriate paragraph

- addOns/help/CHANGELOG.md
- addOns/help/src/main/javahelp/contents/releases/2.17.0.html
- addOns/help/src/main/javahelp/contents/releases/releases.html
- addOns/help/src/main/javahelp/index.xml
- addOns/help/src/main/javahelp/toc.xml
- commonFiles/src/main/resources/map.jhm
As discussed on slack last week.
> Initial 2.17.0 release page
