zaproxy/zap-core-help

src/help/zaphelp/contents/ui/dialogs/advascan.html

advascan typo fix

---

src/help/zaphelp/contents/ui/dialogs/options/pscanrules.html
src/help/zaphelp/contents/ui/dialogs/scanpolicy.html

Clarify Threshold Off  Setting

---

src/help/zaphelp/contents/ui/dialogs/options/keyboard.html

Change from "Rest" to "Reset".

Fix typo in Options Keyboard screen

---

src/help/zaphelp/contents/releases/2_1_0.html

Add issue zaproxy/zaproxy#605.

Update 2.1.0 release help page with fixed issue

---

src/help/zaphelp/contents/start/concepts/sessionManagement.html
src/help/zaphelp/contents/ui/dialogs/session/contexts.html

Change pages "Session Management" and "Session Context screens" to
document the session management method "Http Authentication Session
Management".

Document HTTP session management method

---

src/help/zaphelp/contents/start/concepts/modes.html

Change Modes page to not refer just to the UI, it now applies to daemon
as well.
Part of zaproxy/zaproxy#1590 - Mode to apply when running as a daemon

Update Modes page to match latest code

---

src/help/zaphelp/contents/releases/2_3_0.html
src/help/zaphelp/contents/releases/2_4_0.html

Add issue zaproxy/zaproxy#1119 to 2.3.0 and issue zaproxy/zaproxy#1439
to 2.4.0.

Add fixed issues to old release help pages

---

src/help/zaphelp/contents/start/concepts/alerts.html
src/help/zaphelp/contents/ui/dialogs/options/alert.html

Alert overrides help

---

src/help/zaphelp/contents/ui/dialogs/options/ascaninput.html

Help change for PR zaproxy/zaproxy#2863

Add line re attacking arbitrary query param

---

src/help/zaphelp/contents/ui/dialogs/options/options.html

Help for zaproxy/zaproxy#3007 - its shouldnt be merged until that change is;)

Updated help for the 'Reset to Factory Settings' button

---

src/help/zaphelp/contents/cmdline.html

Change "Command Line" page to document the "-script" command line
argument.

Document script command line argument

---

src/help/zaphelp/contents/releases/2_4_0.html

Add issue zaproxy/zaproxy#1445 to 2.4.0 release page.

Add fixed issue to old release help page

---

src/help/zaphelp/contents/credits.html

As per https://github.com/zaproxy/zap-extensions/pull/614.
Also minor updates as a continued effort on zaproxy/zaproxy#2000

Add Yuji Matsunaga to Credits

---

src/help/zaphelp/contents/credits.html

As per https://github.com/zaproxy/zap-extensions/pull/706.

Add Ravinder Nehra to Credits

---

src/help/zaphelp/contents/credits.html

Per: https://github.com/zaproxy/zaproxy/pull/3151

Add Martin Kalina to Credits

---

src/help/zaphelp/contents/ui/tlmenu/file.html

Accompanying https://github.com/zaproxy/zaproxy/pull/3186 this adds the
"Save As..." details for the file menu

Change to Snapshot As

---

src/help/zaphelp/contents/credits.html

Many thanks to these new contributors :)

Added Artemy Bogdanov, James Kettle, Asif Minhas, Ender Çulha

---

src/help/zaphelp/contents/releases/2_6_0.html

Not confident I've got them all :/

Updated release notes with latest changes

---

src/help/zaphelp/contents/ui/tabs/alerts.html

Update help to include details of the alert panel's new edit alert
button. Corresponding to: https://github.com/zaproxy/zaproxy/pull/3285
Constributes to zaproxy/zaproxy#2595

Add Alert ToolBar Edit Entry

---

src/help/zaphelp/contents/ui/tlmenu/report.html

Add details around "Export Selected URLs to File..." (https://github.com/zaproxy/zaproxy/pull/3340) and "Export URLs for Context" (https://github.com/zaproxy/zaproxy/pull/3235).

Updated URL Export Info

---

src/help/zaphelp/contents/start/concepts/spider.html
src/help/zaphelp/contents/ui/dialogs/options/spider.html

Change pages Spider (concepts) and Options Spider screen, to document
the spider option Accept Cookies.
Part of zaproxy/zaproxy#3395 - Add option to spider anonymously with a
session

Document Accept Cookies spider option

---

src/help/zaphelp/contents/releases/2_7_0.html

In follow-up to: 
https://github.com/zaproxy/zaproxy/pull/3386

Document Updated and New Core Alert Views

---

src/help/zaphelp/contents/credits.html

In follow-up to:
https://github.com/zaproxy/zaproxy/issues/2786#issuecomment-299062418

Add Adrien PAILHES to Credits

---

src/help/zaphelp/contents/credits.html

Add Rafał Ścipień to credits

---

src/help/zaphelp/contents/credits.html

Per: https://github.com/zaproxy/zaproxy/issues/2808

Add Adrian Clay to Credits

---

src/help/zaphelp/contents/credits.html

From zaproxy/zap-api-python#4.

Add Jean Abed to credits

---

src/help/zaphelp/contents/credits.html

From zaproxy/zap-extensions#904.

Add Alexander Zapasnik to credits

---

src/help/zaphelp/contents/credits.html

Add Rodrigo Bonifácio to credits

---

src/help/zaphelp/contents/credits.html

Add the following contributors:
- Omer Levi Hevroni (from zaproxy/zaproxy#3656);
- Anamika Das (from zaproxy/zap-extensions#932).

Update Credits help page

---

src/help/zaphelp/contents/credits.html

Add David Petrasovic to credits

---

src/help/zaphelp/contents/credits.html

Per bugcrowd submission 106936

Add prodigysml to credits

---

src/help/zaphelp/contents/credits.html

Add Liang Mingqiang to credits

---

src/help/zaphelp/contents/credits.html

(And moved James Kettle who was in the wrong place alphabetically;)

Added Juha Kivekäs

---

src/help/zaphelp/contents/credits.html

From zaproxy/zap-extensions#1021.

Add Ailton Caetano to credits

---

src/help/zaphelp/contents/ui/dialogs/options/ascaninput.html

Align with: https://github.com/zaproxy/zaproxy/pull/3805

Update Input Vector Help

---

src/help/zaphelp/contents/credits.html

Add Vladimir Molotkov to credits

---

src/help/zaphelp/contents/ui/dialogs/options/pscanner.html

Update Options Passive Scanner Screen page to reflect latest zaproxy
changes.
Related zaproxy/zaproxy#3958 - Minor Message Clarification

Update label of passive scanner option

---

src/help/zaphelp/contents/credits.html

From zaproxy/zap-extensions#1125.

Add Florent Baillais to credits

---

src/help/zaphelp/contents/ui/dialogs/session/sessprop.html

Change Session Properties dialog page to mention that the Exclude from
Spider option applies to all spiders. Also, correct the case (and remove
word) of the options to match the latest code.

Mention all spiders in Exclude from Spider

---

src/help/zaphelp/contents/releases/2_7_0.html
src/help/zaphelp/contents/start/proxies.html
src/help/zaphelp/contents/ui/dialogs/options/localproxy.html
src/help/zaphelp/contents/ui/dialogs/options/options.html
src/help/zaphelp/contents/ui/dialogs/options/view.html
src/help/zaphelp/toc.xml

https://github.com/zaproxy/zaproxy/pull/4010

Help for ZAP listenning on multiple addresses/ports

---

src/help/zaphelp/contents/start/concepts/concepts.html
src/help/zaphelp/contents/start/concepts/intercept.html
src/help/zaphelp/contents/start/start.html
src/help/zaphelp/index.xml
src/help/zaphelp/toc.xml

Fixes https://github.com/zaproxy/zaproxy/issues/3980

Change Intercepting Proxy to Man-in-the-middle Proxy

---

src/help/zaphelp/contents/releases/2_7_0.html
src/help/zaphelp/contents/releases/releases.html
src/help/zaphelp/index.xml
src/help/zaphelp/map.jhm
src/help/zaphelp/toc.xml

Suggestions for other enhancements that could be mentioned at the start
appreciated :)

Added 2.7.0 release notes

---

src/help/zaphelp/contents/releases/2_6_0.html
src/help/zaphelp/contents/releases/2_7_0.html

Add missing issues to 2.6.0 (1644) and 2.7.0 (4079), remove issue (3594)
not included in 2.7.0 and update issue title (3459).
(Missing issue in 2.6.0 from https://github.com/zaproxy/zap-core-help/pull/146#issuecomment-347152182.)

Update issues in release notes

---

src/help/zaphelp/contents/start/concepts/ascan.html

Add a paragraph about "AddZapHeader.js"
See zaproxy/zaproxy#1429

Issue 1429 - Tweak ascan help

---

src/help/zaphelp/contents/releases/2_8_0.html

Change Release 2.8.0 page to add the new API script views/actions that
allow to manage the script variables.
Part of zaproxy/zaproxy#4135 - REST API to manage script variables

Add new API script actions/views to release notes

---

src/help/zaphelp/contents/ui/dialogs/addalert.html

Reported va Crowdin - thanks to https://crowdin.com/profile/andresitorresm

Fixed typo

---

src/help/zaphelp/contents/credits.html

Add Varsha Venkatesh to credits

---

src/help/zaphelp/contents/credits.html

Add Niranjan Hegde to credits

---

src/help/zaphelp/contents/start/concepts/filters.html
src/help/zaphelp/contents/ui/dialogs/filter.html
src/help/zaphelp/contents/ui/dialogs/resend.html

Restore the previously removed pages to preserve the links for the wiki
pages.

Restore removed pages

---

src/help/zaphelp/contents/ui/dialogs/options/view.html

Change Options Display screen page to mention the option that allows to
choose the look and feel.
Part of zaproxy/zaproxy#2964 - Allow to select the look and feel

Document look and feel option

---

src/help/zaphelp/contents/credits.html

Add Glib Briia to credits

---

src/help/zaphelp/contents/ui/dialogs/options/jvm.html

Related to:
https://github.com/zaproxy/zaproxy/pull/4572
https://github.com/zaproxy/zaproxy/issues/3485

JVM Panel Update For Memory Details

---

src/help/zaphelp/contents/credits.html

From zaproxy/zap-extensions#1534.

Add Kajan Mohanagandhirasa to credits

---

src/help/zaphelp/contents/credits.html

From zaproxy/zap-extensions#1506.

Add Manos Kirtas to credits

---

src/help/zaphelp/contents/ui/tabs/httpsessions.html

Add a bullet outlining the "Find Related Messages" functionality.
Re: https://github.com/zaproxy/zaproxy/pull/4618

Add HttpSessions Context Menu "Find Related Messages" Help

---

src/help/zaphelp/contents/start/concepts/authentication.html

based on [#4682](https://github.com/zaproxy/zaproxy/pull/4682 "support acsrf token in post-based authentication")

help to configure acsrf token in authentication

---

src/help/zaphelp/contents/start/concepts/globalexcludeurl.html
src/help/zaphelp/contents/ui/dialogs/options/globalexcludeurl.html

Global Excludes No Longer Beta

---

src/help/zaphelp/contents/ui/tabs/spider.html

Add description for all the values shown in the Processed column in the
Messages Spider tab.

Document values shown in Messages Spider tab

---

src/help/zaphelp/contents/credits.html

Add Oleksandr Horokh to credits

---

src/help/zaphelp/contents/releases/2_8_0.html
src/help/zaphelp/contents/ui/dialogs/options/ascaninput.html

* ascaninput.html > Updated to cover the functionality of the new option.
* 2_8_0.html > Updated to include the new ascan API end points, and add a note about the change in behavior (query param addition now off by default). Also made one title caps heading tweak.
Per zaproxy/zaproxy#4976

Help update - Optional addition of query param

---

src/help/zaphelp/contents/releases/2_8_0.html

Document the breaking change done to view optionTokensNames.
Part of zaproxy/zaproxy#4993 - Change API view optionTokensNames to
return a list

Document optionTokensNames API breaking change

---

src/help/zaphelp/contents/credits.html

Link also to ZAP's Crawljax repo when mentioning Crawljax.

Mention Crawljax fork in credits

---

src/help/zaphelp/contents/credits.html

Add Joset Zamora to credits

---

src/help/zaphelp/contents/ui/dialogs/options/pscanner.html

Help for https://github.com/zaproxy/zaproxy/pull/5116

Help for new pscan maxAlerts option

---

src/help/zaphelp/contents/credits.html

From zaproxy/zap-extensions#1890.

Add Tushar Aggarwal to credits

---

src/help/zaphelp/contents/credits.html

From zaproxy/zap-extensions#1878.

Add Yvan Phélizot to credits

---

src/help/zaphelp/contents/ui/dialogs/options/connection.html

Align with https://github.com/zaproxy/zaproxy/pull/5132
Part of zaproxy/zaproxy#2000

Connection Options Title Caps Tweaks

---

src/help/zaphelp/contents/credits.html

Add Jonathan Ness to credits

---

src/help/zaphelp/contents/ui/dialogs/options/certificate.html

In follow-up to https://github.com/zaproxy/zaproxy/pull/4892

Add help for setting Client Cert via CLI

---

src/help/zaphelp/contents/releases/2_8_0.html
src/help/zaphelp/contents/ui/dialogs/options/view.html

In support of https://github.com/zaproxy/zaproxy/pull/4617

Update Help With Font Options

---

src/help/zaphelp/contents/start/concepts/callbacks.html
src/help/zaphelp/contents/ui/dialogs/options/callback.html
src/help/zaphelp/contents/ui/overview.html
src/help/zaphelp/contents/ui/tabs/callbacks.html
src/help/zaphelp/index.xml
src/help/zaphelp/map.jhm
src/help/zaphelp/toc.xml

Per https://github.com/zaproxy/zaproxy/pull/3930 & [IRC discussion](https://mozilla.logbot.info/websectools/20190109)

Add help for Callbacks tab

---

src/help/zaphelp/contents/credits.html

Add Taras Ivashchenko to credits

---

src/help/zaphelp/contents/credits.html

Add Bilal Achahbar to credits

---

src/help/zaphelp/contents/credits.html

Add Matthias Altmann to credits

---

addOns/help/src/main/javahelp/contents/credits.html

Add Yashvendra Kashyap to credits

---

addOns/help/src/main/javahelp/contents/ui/tlmenu/import.html
addOns/help/src/main/javahelp/contents/ui/tlmenu/tlmenu.html

Add a page for the Import menu.
Mention the menu in the Top Level Menu page.
Part of #5256 - Added Import top-level Menu

Add page for Import top level menu

---

addOns/help/src/main/javahelp/contents/credits.html

Per https://github.com/zaproxy/zaproxy/pull/5266#issuecomment-476596737

Add Gustavo Mitsuichi

---

addOns/help/src/main/javahelp/contents/credits.html

Add Javan Rasokat to credits

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#1981.

Add Chaitanya Sharma to credits

---

addOns/help/src/main/javahelp/contents/credits.html

See: https://github.com/zaproxy/zap-extensions/pull/2000

Add tjtanjin to credits

---

README.md
addOns/help/src/main/javahelp/contents/intro.html
addOns/help/src/main/javahelp/contents/pentest/pentest.html
addOns/help/src/main/javahelp/contents/ui/overview.html
addOns/help/src/main/javahelp/contents/ui/tlmenu/help.html
addOns/help/src/main/javahelp/helpset.hs
addOns/help/src/main/javahelp/toc.xml

In order to distinguish it from the HUD :)

Rebrand to ZAP Desktop UI

---

addOns/help/src/main/javahelp/contents/credits.html

Added Daniel Thompson-Yvetot

---

addOns/help/src/main/javahelp/contents/cmdline.html

Added -silent cmdline option

---

addOns/help/help.gradle.kts
addOns/help/src/main/javahelp/contents/releases/2_8_0.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml
commonFiles/src/main/resources/map.jhm

Should we be drawing attension to any other changes?

Updated the 2.8.0 release notes

---

.github/main.workflow
addOns/addOns.gradle.kts
commonFiles/commonFiles.gradle.kts
gradle/wrapper/gradle-wrapper.properties

Update Gradle to 5.4.1 and add-on plugin to 0.2.0.
Update build accordingly.
Add GitHub Actions workflow and Gradle task to release on tag.
---
WIP until zaproxy is updated (zaproxy/zaproxy#5369).

Update Gradle and add-on plugin

---

addOns/help/src/main/javahelp/contents/releases/2_8_0.html

Mention the libraries that will be removed and the ones that were
updated.
Part of zaproxy/zaproxy#4780 - Tidy up dependencies

Update release notes with latest lib changes

---

addOns/addOns.gradle.kts

The add-ons included in main and weekly releases will be defined in the
zaproxy repo.

Remove main/weekly release related tasks

---

addOns/addOns.gradle.kts

Check that the tag matches the expected format.

Validate tag for releases

---

addOns/help/CHANGELOG.md

We'll update and release the others once we've re-enabled the Crowdin integration.

Release English help file

---

addOns/help/CHANGELOG.md
addOns/help/help.gradle.kts

help: prepare next dev iteration

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zap-extensions/pull/2062

Add Markus Kiss to credits

---

addOns/help/src/main/javahelp/contents/releases/releases.html

Include 2.8.0 in releases page

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zap-extensions/pull/2146#issuecomment-522386097

Add preetkaran20

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/ascan.html

As per: https://github.com/zaproxy/zaproxy/pull/5558

Update scan options

---

addOns/help/src/main/javahelp/contents/credits.html

Add Justin Matte to credits

---

addOns/help/src/main/javahelp/contents/credits.html

Per https://github.com/zaproxy/zaproxy/pull/5567

Add Zainab Al Showely

---

addOns/help/src/main/javahelp/contents/credits.html

Added Michael Gabriel

---

addOns/help/CHANGELOG.md
addOns/help/src/main/javahelp/contents/releases/2_9_0.html
addOns/help/src/main/javahelp/contents/releases/releases.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml
commonFiles/src/main/resources/map.jhm

Add (initial) page for 2.9.0 release, mentioning:
- Libraries changes/updates;
- Removal of filter code.

Add 2.9.0 release notes

---

addOns/help/src/main/javahelp/contents/releases/2_9_0.html

Document new `addAlert` and `updateAlert` API end points, in follow-up to: https://github.com/zaproxy/zaproxy/pull/5664

Update 2.9.0 release notes with added Alert api details

---

addOns/help/src/main/javahelp/contents/releases/2_9_0.html
addOns/help/src/main/javahelp/contents/start/concepts/sessionManagement.html
addOns/help/src/main/javahelp/contents/ui/dialogs/session/contexts.html

Help for session management scripts

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/dynsslcert.html

Per discussion in: https://github.com/zaproxy/zaproxy/pull/5714

iOS root cert full trust details

---

addOns/help/src/main/javahelp/helpset.hs

Change main HelpSet to use as home the Introduction page.
Fix zaproxy/zaproxy#5753.

Make Introduction the home page

---

addOns/help/src/main/javahelp/contents/ui/tlmenu/edit.html

Per: https://github.com/zaproxy/zaproxy/pull/5747
Also removed a spurious period in the content, and added an oxford comma.

Help: Update TL Menu Edit search details

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/ascan.html

spelling: minutes; 0 is unlimited

---

addOns/help/src/main/javahelp/contents/releases/2_9_0.html
addOns/help/src/main/javahelp/contents/ui/dialogs/advascan.html

Signed-off-by: karan preet singh sasan <karanpreet_singh@intuit.com>

Adding release note for Active Scan Filtering enhancement

---

addOns/help/src/main/javahelp/contents/releases/1_0_0.html
addOns/help/src/main/javahelp/contents/releases/1_3_0.html
addOns/help/src/main/javahelp/contents/releases/2_2_0.html
addOns/help/src/main/javahelp/contents/releases/2_6_0.html
addOns/help/src/main/javahelp/contents/releases/2_8_0.html
addOns/help/src/main/javahelp/contents/start/concepts/breakpoints.html
addOns/help/src/main/javahelp/contents/start/concepts/concepts.html
addOns/help/src/main/javahelp/contents/start/concepts/intercept.html
addOns/help/src/main/javahelp/contents/ui/dialogs/addbreak.html
addOns/help/src/main/javahelp/contents/ui/dialogs/dialogs.html
addOns/help/src/main/javahelp/contents/ui/dialogs/options/breakpoints.html
addOns/help/src/main/javahelp/contents/ui/overview.html
addOns/help/src/main/javahelp/contents/ui/tabs/break.html
addOns/help/src/main/javahelp/contents/ui/tabs/breakpoints.html
addOns/help/src/main/javahelp/contents/ui/tabs/history.html
addOns/help/src/main/javahelp/contents/ui/tabs/sites.html
addOns/help/src/main/javahelp/contents/ui/tltoolbar.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml

spelling: breakpoint

---

addOns/help/src/main/javahelp/contents/releases/2_9_0.html

Update 2.9.0 release notes with closed issues.

Add issues closed in 2.9.0

---

addOns/help/src/main/javahelp/contents/credits.html

Added Nirojan

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zap-hud/pull/647#issuecomment-567244097

Add Josh Soref to the credits

---

addOns/help/src/main/javahelp/contents/releases/2_9_0.html

Add new pscan API endpoints to release notes

---

addOns/help/src/main/javahelp/contents/start/pentest.html
addOns/help/src/main/javahelp/contents/start/start.html
commonFiles/src/main/resources/map.jhm

Move to start directory, it's listed under that page in the TOC.

Relocate pentest.html

---

addOns/help/src/main/javahelp/contents/releases/2_9_0.html

Update 2.9.0 release notes with latest closed issues.

Add more issues closed in 2.9.0

---

addOns/help/src/main/javahelp/contents/intro.html

Update online help link to point to zaproxy site.
Remove unnecessary paragraph and line break at the end of the page.

Tweak intro page

---

addOns/help/src/main/javahelp/contents/start/features/addons.html
addOns/help/src/main/javahelp/contents/ui/dialogs/manageaddons.html

Link to the site instead of zap-extensions.

Update marketplace links

---

addOns/help/CHANGELOG.md
addOns/help/src/main/javahelp/contents/intro.html
addOns/help/src/main/javahelp/contents/releases/2.4.1.html
addOns/help/src/main/javahelp/contents/releases/2.6.0.html

Update for new website

---

addOns/help/CHANGELOG.md
addOns/help/src/main/javahelp/contents/releases/2.9.0.html

Add release date and link to tag.
Add latest issue fixed to release notes.

help: prepare release

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zap-extensions/pull/2199

Add Bunyanuch Saengnet to credits

---

addOns/help/src/main/javahelp/contents/credits.html

Link to GitHub project, the site is no longer active.

Update Crawljax link

---

addOns/help/src/main/javahelp/contents/credits.html

Add Ahmed Bahajjaj to credits

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/dynsslcert.html

Use code tags instead of quotes, per: https://github.com/zaproxy/zaproxy-website/issues/47

Minor Punctuation Fix

---

addOns/help/src/main/javahelp/contents/credits.html

Promoted Nirojan :)

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#2200.

Add Savva Kodeikin to credits

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/connection.html

Update Options Connection screen with description of SOCKS proxy
configuration.
Part of #29 - SOCKS (outgoing) proxy support

Add help for SOCKS proxy configuration

---

addOns/help/src/main/javahelp/contents/start/features/features.html
addOns/help/src/main/javahelp/contents/start/features/intercept.html
addOns/help/src/main/javahelp/contents/start/start.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml

Justification : https://twitter.com/psiinon/status/1290229663713726467

Changed to use manipulator-in-the-middle

---

addOns/help/src/main/javahelp/contents/credits.html

Add Stefan Tobler to credits

---

addOns/help/src/main/javahelp/contents/releases/2.10.0.html
addOns/help/src/main/javahelp/contents/releases/releases.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml
commonFiles/src/main/resources/map.jhm

Developments, issues and libs are up to date as of now.
Need to add API changes and summary of significant changes.
It can be merged as is or left open as WIP, fine either way.

Add 2.10.0 release notes

---

addOns/help/src/main/javahelp/contents/start/features/contexts.html
addOns/help/src/main/javahelp/contents/start/features/ddc.html
addOns/help/src/main/javahelp/contents/start/features/features.html
addOns/help/src/main/javahelp/contents/start/features/scripts.html
addOns/help/src/main/javahelp/contents/start/features/sitestree.html
addOns/help/src/main/javahelp/contents/start/features/structmods.html
addOns/help/src/main/javahelp/contents/start/features/structparams.html
addOns/help/src/main/javahelp/contents/ui/tabs/sites.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml
commonFiles/src/main/resources/map.jhm

Update help with site tree and scripts

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/pscanner.html

Help for https://github.com/zaproxy/zaproxy/pull/6226

Add help for max body size to scan

---

addOns/help/src/main/javahelp/contents/credits.html

Also linked Rick's name to his twitter acc ;)

Added Akshath to core team

---

addOns/help/src/main/javahelp/contents/credits.html

Add Christian Koidl to credits

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zap-extensions/pull/2568

Add Eswarprasath Jayaraman to the credits

---

addOns/help/src/main/javahelp/contents/start/features/authentication.html
addOns/help/src/main/javahelp/contents/start/features/authmethods.html
addOns/help/src/main/javahelp/contents/start/features/authstrategies.html
addOns/help/src/main/javahelp/contents/start/features/features.html
addOns/help/src/main/javahelp/contents/start/features/stats.html
addOns/help/src/main/javahelp/contents/start/features/users.html
addOns/help/src/main/javahelp/contents/ui/dialogs/session/context-auth.html
addOns/help/src/main/javahelp/contents/ui/dialogs/session/context-struct.html
addOns/help/src/main/javahelp/contents/ui/dialogs/session/contexts.html
addOns/help/src/main/javahelp/contents/ui/dialogs/session/sessprop.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml
commonFiles/src/main/resources/map.jhm

I've created 2 new help pages and moved some of the content into those:
- Features / Authentication Methods
- Features / Authentication Verification Strategies

Help for auth polling

---

addOns/help/src/main/javahelp/contents/releases/2.10.0.html

Updated the enhancements/bugs and added placeholders for some of the significant changes - feel free to add more!

2.10 release note updates

---

addOns/help/src/main/javahelp/contents/releases/2.10.0.html

Hacked a quick standalone script to dump all of the API endpoints, ran vs 2.9 and dev then diffed them :)

Added new API endpoints

---

addOns/help/src/main/javahelp/contents/start/features/custompages.html
addOns/help/src/main/javahelp/contents/ui/dialogs/session/contexts.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml
commonFiles/src/main/resources/map.jhm

- contexts.html > Added a summary of Custom Page functionality.
- custompages.html > New Custom Page details and config example.
- index.xml, map.jhm, toc.xml > Reference new page.
Fixes zaproxy/zaproxy#9.

Add Custom Page help

---

addOns/help/src/main/javahelp/contents/releases/2.10.0.html

Mention SOCKS proxy configuration and cached scripts.

Document new features in 2.10 rel notes

---

addOns/help/src/main/javahelp/contents/releases/2.10.0.html

Include more issues addressed and remove one not included in 2.10.

Update issues in 2.10 rel notes

---

addOns/help/src/main/javahelp/contents/releases/2.10.0.html

Add issue to 2.10 rel notes

---

addOns/help/src/main/javahelp/contents/releases/2.10.0.html

2.10 release notes - add new add-ons

---

addOns/addOns.gradle.kts
addOns/help/CHANGELOG.md
addOns/help/help.gradle.kts
addOns/help/src/main/javahelp/contents/releases/2.10.0.html

Includes last min updates to the release notes to cover the updated add-ons and docker changes.

2.10 release

---

addOns/help/CHANGELOG.md
addOns/help/help.gradle.kts
addOns/help/src/main/javahelp/contents/start/features/spider.html

Update version and changelog.
Remove extra column in a videos table.

help: prepare next dev iter and tweak table

---

addOns/help/CHANGELOG.md
addOns/help/src/main/javahelp/contents/releases/2.10.0.html

Use main branch instead of develop.

Update reference to zaproxy repo

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zap-extensions/pull/2777#issuecomment-804090876

Add pranavsaxena17

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zap-extensions/pull/2705#issuecomment-821333894

Add CravateRouge

---

.github/workflows/ci.yml

Use `main` branch instead of `master`.

Update branch in CI workflow

---

addOns/help/src/main/javahelp/contents/credits.html

Added Florian Beijers

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/certificate.html

Improving the documentation in regards with https://github.com/zaproxy/zaproxy/pull/6614

Improve documentation for Client Certificate authentication

---

addOns/help/CHANGELOG.md
addOns/help/src/main/javahelp/contents/releases/2.10.0.html

Update link to community-scritps repo

---

addOns/help/src/main/javahelp/contents/credits.html

Credits: added Scott Gerlach

---

addOns/help/src/main/javahelp/contents/credits.html

Per:https://github.com/zaproxy/zap-extensions/pull/2961#issuecomment-863485300

Add Erik de Kuijper

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zap-extensions/pull/2913#issuecomment-873908066

Add Adam Baldwin

---

addOns/help/src/main/javahelp/contents/credits.html

Move Nirojan to extended team

---

addOns/help/src/main/javahelp/contents/cmdline.html
addOns/help/src/main/javahelp/contents/start/features/authmethods.html
addOns/help/src/main/javahelp/contents/start/features/stats.html
addOns/help/src/main/javahelp/contents/ui/tlmenu/report.html

Update help for manual auth, stats and reporting

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/ascan.html

Help changes for https://github.com/zaproxy/zaproxy/pull/6803

Acsrf handling on by default in ascan

---

addOns/help/src/main/javahelp/contents/releases/2.11.0.html
addOns/help/src/main/javahelp/contents/releases/releases.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml
commonFiles/src/main/resources/map.jhm

Obviously will need to update these before the actual release :)

Initial 2.11.0 release notes

---

addOns/help/src/main/javahelp/contents/releases/2.11.0.html

2.11 Release notes - new add-ons and corrected issues

---

addOns/help/src/main/javahelp/contents/releases/2.11.0.html

Added more details of the significant changes.

---

addOns/help/src/main/javahelp/contents/ui/dialogs/addalert.html

Part of https://github.com/zaproxy/zaproxy/issues/5061.
Signed-off-by: Akshath Kothari <ricekot@gmail.com>

Document missing alert fields

---

addOns/help/src/main/javahelp/contents/releases/2.11.0.html

Mention the (api) libraries updated.

Add changed libraries to release notes

---

addOns/help/src/main/javahelp/contents/releases/2.11.0.html

Mention the endpoints added and deprecated.

Add ZAP API changes to release notes

---

addOns/help/src/main/javahelp/contents/releases/2.11.0.html

Update release notes with latest issues

---

addOns/help/src/main/javahelp/contents/releases/2.11.0.html
addOns/help/src/main/javahelp/contents/releases/releases.html

2.11 Rel notes - OWASP 20th anniversary + docker changes

---

addOns/help/src/main/javahelp/contents/releases/2.11.0.html

To reflect that they've been added for all scan rules.

2.11 Release notes - tweaks alert tags section

---

addOns/help/src/main/javahelp/contents/releases/2.11.0.html

2.11 release notes : add statistics details

---

addOns/help/src/main/javahelp/contents/credits.html

Just for the core team that is.

Add sponsorship links to the credits

---

addOns/help/src/main/javahelp/contents/releases/2.11.0.html

Release notes - report section tweak

---

addOns/addOns.gradle.kts
build.gradle.kts

Use main ZAP version

---

addOns/help/CHANGELOG.md
addOns/help/gradle.properties
addOns/help/src/main/javahelp/contents/releases/2.11.1.html
addOns/help/src/main/javahelp/contents/releases/releases.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml
commonFiles/src/main/resources/map.jhm

Integrate changes done in versions 13 and 14 of main help add-on to
main branch.
Bump version.

Merge releases help-v13 and 14 into main

---

README.md

Removed the links to the old wiki translations

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html

Add section for binary incompatible changes and mention the classes
that were removed.

Mention incompatible changes in release notes

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html

Help changes associated with https://github.com/zaproxy/zaproxy/pull/7067

Updated help with 2.2.0 / 2.3.0 deprecations

---

addOns/help_ru_RU/CHANGELOG.md
addOns/help_ru_RU/gradle.properties
addOns/help_ru_RU/help_ru_RU.gradle.kts

Promote and release Russian help

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html

Update to help to correspond to changes in zap repo

Update 2.12.0 release notes with deprecated code

---

addOns/help/src/main/javahelp/contents/credits.html

Looks like we missed this on his previous PRs :/

Add KC Berg

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html

Help changes for [#7106](https://github.com/zaproxy/zaproxy/issues/7106)
Signed-off-by: Hichem Yagoubi <hichem.yagoubi@etu.usthb.dz>

Updated help with 2.6.x deprecations

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html

Release Notes for Alert API fix - https://github.com/zaproxy/zaproxy/issues/7079
Signed-off-by: LakiG <garg.lakshya@gmail.com>

Add alert API release notes 2.12.0

---

addOns/help/src/main/javahelp/contents/start/features/spider.html

Part of https://github.com/zaproxy/zaproxy/issues/7149.

Add new spidered HTML elements and attributes

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/pscanrules.html
addOns/help/src/main/javahelp/contents/ui/dialogs/scanpolicy.html

chore: Tweak threshold explanation

---

addOns/help/src/main/javahelp/contents/start/features/spider.html

Related to: zaproxy/zaproxy#7169

Add embed src to spider help

---

addOns/help/src/main/javahelp/contents/releases/2.8.0.html
addOns/help/src/main/javahelp/contents/start/features/breakpoints.html
addOns/help/src/main/javahelp/contents/ui/dialogs/addbreak.html
addOns/help/src/main/javahelp/contents/ui/tabs/sites.html

Related to: zaproxy/zaproxy#7205 and similarly going along with my old writing rant: http://andore.ddns.net

chore: Remove use of "and/or"

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html

See https://github.com/zaproxy/zaproxy/pull/7206.
Signed-off-by: ricekot <github@ricekot.com>

Update release notes for ascan / pscan endpoints

---

addOns/help/src/main/javahelp/contents/start/features/anticsrf.html
addOns/help/src/main/javahelp/contents/start/features/pscan.html
addOns/help/src/main/javahelp/contents/ui/footer.html

Clarify a few places where "scanners" is used generically but may not be entirely accurate.

chore: Reduce use "scanners"

---

addOns/help/src/main/javahelp/contents/releases/2.3.0.html
addOns/help/src/main/javahelp/contents/releases/2.4.0.html
addOns/help/src/main/javahelp/contents/releases/2.5.0.html
addOns/help/src/main/javahelp/contents/start/checks.html
addOns/help/src/main/javahelp/contents/start/features/addons.html
addOns/help/src/main/javahelp/contents/ui/dialogs/options/checkforupdates.html

Related to zaproxy/zaproxy#4732

chore: Standardize on the use of "status" vs "quality"

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#3884.

Add Siddharth Singh to credits

---

addOns/help/src/main/javahelp/contents/credits.html

Apply changes done in the website: zaproxy/zaproxy-website#1069

Sync credits page

---

addOns/help/src/main/javahelp/contents/credits.html

Credits: Added Karthik

---

addOns/help/src/main/javahelp/contents/start/features/custompages.html

Following: https://github.com/zaproxy/zaproxy/pull/7207

Update Custom Pages Help

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html
addOns/help/src/main/javahelp/contents/ui/dialogs/options/pscanner.html

Help changes for https://github.com/zaproxy/zaproxy/pull/7475

Pscan - clear queue

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html

Part of zaproxy/zaproxy#3113 based on https://www.zaproxy.org/blog/2022-08-30-spider-move/

Spider related updates for 2.12 release notes

---

addOns/help/src/main/javahelp/contents/ui/tlmenu/file.html

Help for [#6735](https://github.com/zaproxy/zaproxy/issues/6735)
Signed-off-by: Hichem Yagoubi <hichem.yagoubi@etu.usthb.dz>

Add open recent menu help

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html

Following: https://github.com/zaproxy/zap-extensions/pull/3979
Related to: https://github.com/zaproxy/zaproxy/pull/7433
Part of: https://github.com/zaproxy/zaproxy/issues/6579

Add HAR API deprecation details

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html

Update 2.12 release notes for bit.ly removal

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html

And DOM XSS ;)
Depends on https://github.com/zaproxy/zap-extensions/pull/4118 and https://github.com/zaproxy/zap-extensions/pull/4121
Will also need to be updated for ascan promotions...

2.12 Release notes - inc scan rule promotions

---

addOns/help/src/main/javahelp/contents/credits.html

For Spanish translations.
Also added some new lines to make the Spanish entry a bit easier to maintain 😉 

Credits: Added Surgat

---

addOns/help/src/main/javahelp/contents/releases/2.12.0.html
addOns/help/src/main/javahelp/contents/releases/releases.html

Update for hsqldb 2.7.1

---

addOns/addOns.gradle.kts
build.gradle.kts

Update ZAP to 2.12

---

settings.gradle.kts

Workaround issues with Gradle Plugin Portal.

Fallback to Maven Central when resolving plugins

---

addOns/help/CHANGELOG.md
addOns/help/src/main/javahelp/contents/releases/2.12.0.html

Added Desktop HTML Injection Fix section

---

addOns/help/src/main/javahelp/contents/credits.html

As per https://github.com/zaproxy/zap-hud/pull/1177#issuecomment-1404642787

Credits: Add Vitika Soni

---

addOns/help/src/main/javahelp/contents/ui/tabs/history.html

Related to: zaproxy/zaproxy#7675

Add 'Jump to History ID...' content

---

addOns/help/src/main/javahelp/contents/start/features/scripts.html
addOns/help/src/main/javahelp/contents/ui/dialogs/manageaddons.html
addOns/help/src/main/javahelp/contents/ui/dialogs/options/ascan.html
addOns/help/src/main/javahelp/contents/ui/dialogs/options/checkforupdates.html
addOns/help/src/main/javahelp/contents/ui/tlmenu/help.html

Follow-up to zaproxy/zaproxy#7722

help: Align with core string/title changes

---

addOns/help/src/main/javahelp/contents/start/features/modes.html
addOns/help/src/main/javahelp/contents/ui/tltoolbar.html

Follow-up to: zaproxy/zaproxy#7728

Titlecaps Follow-up

---

addOns/help/src/main/javahelp/contents/credits.html

Signed-off-by: Vitika9 <vitika.program@gmail.com>

Credits: Update Vitika Soni's username

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#4409.

Add Aryan Gupta to credits

---

addOns/help/src/main/javahelp/contents/credits.html

Per:
- https://github.com/zaproxy/zap-extensions/pull/4362#issuecomment-1464978538
- https://github.com/zaproxy/zap-extensions/pull/4338#issuecomment-1465217454

Add contributors

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#4478.

Add Sparsh Sethi to credits

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#4477.

Add Chandaluri Vamsi Krishna to credits

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zap-extensions/pull/4537#issuecomment-1501716064

Add Giothysham

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#4547.

Add André Alves to credits

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#4567.

Add GRVial to credits

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#4585.

Add Yang Bai to credits

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/ascan.html

Mention the new option in the Options Active Scan screen.
Part of zaproxy/zaproxy#7869.

Document max alerts per active scan rule

---

addOns/help/src/main/javahelp/contents/credits.html

- https://github.com/zaproxy/zap-extensions/pull/4625
- https://github.com/zaproxy/zap-extensions/pull/4624
- https://github.com/zaproxy/zap-extensions/pull/4605

Add Thiago Gomes, ciceroff and Chris Dailey

---

addOns/help/CHANGELOG.md
addOns/help/help.gradle.kts
addOns/help/src/main/javahelp/contents/releases/2.13.0.html
addOns/help/src/main/javahelp/contents/releases/releases.html
addOns/help/src/main/javahelp/index.xml
commonFiles/src/main/resources/map.jhm

Add initial content:
- Dependency updates.
- Added add-on.
- Issues closed.

Add release notes for 2.13.0

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#4011.

Add Patrick Double to credits

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#4439.

Add Laurent Laubin to credits

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#4765.

Add Shershon A J to credits

---

README.md
RELEASING.md

Update link to Crowdin project and name.

Update another link and name

---

addOns/help/src/main/javahelp/contents/cmdline.html

Update to match the newer location.
Related to zaproxy/zaproxy#7996.

Update Windows installation path

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zap-extensions/pull/4833#issuecomment-1712525058 and https://github.com/zaproxy/zap-extensions/pull/4865#issuecomment-1713168442

Add gustavocovas and FiveOFive

---

addOns/addOns.gradle.kts
addOns/help/CHANGELOG.md
addOns/help/src/main/javahelp/contents/releases/2.14.0.html
addOns/help/src/main/javahelp/contents/releases/releases.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml
commonFiles/src/main/resources/map.jhm

Add initial content:
- Dependency updates.
- Added add-on.
- Issues closed.

Add release notes for 2.14.0

---

addOns/help/src/main/javahelp/contents/releases/2.14.0.html

Use `ul` and `li` elements.
---
Reported in IRC.

Fix listing in release notes

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#5007.

Add drighty to credits

---

addOns/help/src/main/javahelp/contents/credits.html

Add Sébastien Amelinckx to credits

---

addOns/help/src/main/javahelp/contents/ui/tabs/httpsessions.html

Drop "to Clipboard" from ZAP copy menu items

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#5115.

Add Divyansh Jain to credits

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#5094.

Add Amit Panwar to credits

---

addOns/help/src/main/javahelp/contents/credits.html

From zaproxy/zap-extensions#5198.

Add Ganesh Dagadi to credits

---

addOns/help/CHANGELOG.md
addOns/help/src/main/javahelp/contents/releases/2.15.0.html
addOns/help/src/main/javahelp/contents/releases/releases.html
addOns/help/src/main/javahelp/index.xml
addOns/help/src/main/javahelp/toc.xml

Initial 2.15.0 release page

---

addOns/addOns.gradle.kts

Use latest version to allow filtering translated files.

Update Gradle Crowdin plugin

---

addOns/help/src/main/javahelp/contents/releases/2.15.0.html
addOns/help/src/main/javahelp/contents/ui/dialogs/options/script.html
commonFiles/src/main/resources/map.jhm

May add more items for last min additions..

2.15 Release note update

---

addOns/help/src/main/javahelp/contents/credits.html

Per https://github.com/zaproxy/zap-extensions/pull/4565#issuecomment-2238240242

Add Aayush Yadav

---

addOns/help/src/main/javahelp/contents/credits.html

Per: https://github.com/zaproxy/zaproxy/issues/8592#issuecomment-2305062438

Add Pyae Hlian Moe to credits

---

addOns/help/src/main/javahelp/contents/credits.html

Ref:
- https://github.com/zaproxy/zaproxy-website/pull/2859
- https://github.com/zaproxy/zap-extensions/pull/5883

Add Dragos-Stefan Necula to credits

---

addOns/help/src/main/javahelp/contents/start/features/authentication.html
addOns/help/src/main/javahelp/contents/start/features/httpsessions.html
addOns/help/src/main/javahelp/contents/start/pentest.html
addOns/help/src/main/javahelp/contents/start/proxies.html
addOns/help/src/main/javahelp/contents/ui/tlmenu/edit.html

And other misc changes I happened to notice :grin:

Dont automate forced user mode

---

addOns/help/src/main/javahelp/contents/releases/2.16.0.html

Update the list of enhancements and bugs addressed.

Add latest issues addressed in 2.16

---

addOns/help/src/main/javahelp/contents/ui/dialogs/options/ascaninput.html

Related to: zaproxy/zaproxy#8911

Add content for "Plain Body Data" input vector

---

addOns/help/CHANGELOG.md
addOns/help/src/main/javahelp/contents/start/features/breakpoints.html

Fix typo in breakpoints.html
